---
- set_fact:
    net_backup_dir: "{{ playbook_dir }}/backups"
  when: net_backup_dir is not defined

- set_fact:
    net_backup_file: "{{ net_backup_dir }}/{{ inventory_hostname }}.cfg"
    net_backup_force: "{{ net_backup_force | default('no') }}"
    net_backup_fail_on_change: "{{ net_backup_fail_on_change | default('no') }}"
    net_backup_on_change: "{{ net_backup_on_change | default('yes') }}"

- name: Check to see if the backup file exists
  stat:
    path: "{{ net_backup_file }}"
  register: stat_result

- block:
    - include_tasks: "{{ ansible_network_os }}-diff-config.yml"
    - debug: msg="Configuration has changed."
      when: diff_results.changed
  when: stat_result.stat.exists

- debug: var=stat_result

- include_tasks: "{{ ansible_network_os }}-backup-config.yml"
  when: (stat_result.stat.exists == false)

- block:
    - name: Copy the temp to the destination
      copy:
        src: "{{ temp_backup_file }}"
        dest: "{{ net_backup_file }}"
        backup: yes
        force: "{{ net_backup_force | default('no') }}"

    - name: Delete the temp file
      file:
        path: "{{ temp_backup_file }}"
        state: absent
      changed_when: False

  when: (stat_result.stat.exists|bool == false)
