---
- name: Enable Netconf service
  iosxr_netconf:
    netconf_port: 830
    netconf_vrf: 'default'
    state: present
  connection: network_cli

- name: configure hostname and domain name
  iosxr_system:
    hostname: "{{ inventory_hostname }}"
    domain_name: "{{ dns_domain_name | default(omit) }}"
    domain_search: "{{ dns_domain_search | default(omit) }}"
    lookup_source: "{{ dns_lookup_source | default(omit) }}"
    lookup_enabled: "{{ dns_lookup_enabled | default(omit) }}"
    name_servers: "{{ dns_name_servers | default(omit) }}"
  connection: netconf
