---
- name: Enable netconf service on port 830
  junos_netconf:
    listens_on: 830
    state: present

# - name: Configure root password and enable netconf
#   junos_config:
#     lines:
#       - set system root-authentication encrypted-password itreallydontmatter
#       - set system services netconf ssh
#     comment: enable netconf
#     confirm_commit: yes
#   connection: netconf

- name: configure hostname and domain name
  junos_system:
    hostname: "{{ inventory_hostname }}"
    domain_name: "{{ dns_domain_name | default(omit) }}"
    domain_search: "{{ dns_domain_search | default(omit) }}"
    lookup_source: "{{ dns_lookup_source | default(omit) }}"
    lookup_enabled: "{{ dns_lookup_enabled | default(omit) }}"
    name_servers: "{{ dns_name_servers | default(omit) }}"
  connection: netconf
