---
- name: configure hostname and domain name
  nxos_system:
    hostname: "{{ inventory_hostname }}"
    domain_name: "{{ dns_domain_name | default(omit) }}"
    domain_search: "{{ dns_domain_search | default(omit) }}"
    lookup_source: "{{ dns_lookup_source | default(omit) }}"
    lookup_enabled: "{{ dns_lookup_enabled | default(omit) }}"
    name_servers: "{{ dns_name_servers | default(omit) }}"
