---
- name: Get BIG-IP facts
  bigip_facts:
    server: "{{ ansible_host }}"
    user: "{{ network_username }}"
    password: "{{ network_password }}"
    validate_certs: no
    include: "system_info,software,self_ip"
  register: bigip_facts
  delegate_to: localhost

- debug: var=bigip_facts
  delegate_to: localhost
