---
- name: Show IOS facts
  hosts: routers
  connection: local
  gather_facts: False
  tasks:

    - name: Get facts
      ios_facts:
        gather_subset: all
      register: ios_facts

    - debug: var=ios_facts
